### PR TITLE
Simon Game

### PR DESCRIPTION
**Pull request by SOMNATH0904**
This Game is created using HTML, CSS & Javascript ...

### CODE REVIEW

**Comment by SOMNATH0904** [comment]
Please merge this project under Hactoberfest 2023 ....

**Comment by Harshit-Raj-14** [comment]
Hello @SOMNATH0904 I actually tried playing the game you made. I think the color changes are too fast and no one is able to see on which block color change happened and how many times. To make the game fun you should add more directions like when the player should start playing and when he should observe to remember the pattern.

Let's see the project to completion and make a good contribution. Best of luck.

**Comment by SOMNATH0904** [comment]
@Harshit-Raj-14 Actually the colours I have used, I think they are almost okay ... Actually, for starting the game purpose we have to click outside the box so that our game starts ... And after that it will blink with white colour ... And after that when there will be increase in the levels then it will be shown with green colour ... And timings I have given are approx 1 s type ... So, for now it's my request that please accept it for the Hactoberfest event ... But yeah, since you told me to do the corrections, I will definitely do all of these but before this I have one request that please accept it for the event as the event is also going to end in 4-5 days ... Thank you!

**Comment by Harshit-Raj-14** [comment]
@SOMNATH0904 Ok accepted. Since you worked to make the project. Those were just some suggestions I made as a user. Otherwise the project works fine. Also, you can make more contributions here.

**Comment by SOMNATH0904** [comment]
@Harshit-Raj-14 Thank You for your understanding!

**Comment by SOMNATH0904** [comment]
Happy to Contribute

**Pull request merged**
