### PR TITLE
Refactored Code/Also added style.css

### PR DESCRIPTION
**Pull request by WolfSlayer2**
### Minor changes in UI, Added style.css file and some more fixes.

### CODE REVIEW

**Comment by Harshit-Raj-14** [comment]
Hello, thanks for your contribution. But to make this a valuable contribution can you do the following:
> Currently if you hover on the "More about this zone" button you the text becomes invisible. Make the text color change as well so that it remains visible even when you hover on it. Or, provide a better solution if you have something else in mind.

> Inside the alarm clock folder add a Readme.md file with the following details : project name, tech stack used, a short description and features of project written point-wise, and a live link of the project hosted on github.

Once you do the following changes I will merge the PR and label it as hacktoberfest accepted.

Looking forward to your contribution.

Do contact me if you need help.

**Comment by WolfSlayer2** [comment]
sure i will look into it.

**Comment by WolfSlayer2** [comment]
Fixed the button text color on hover. Also added Readme.md

**Comment by Harshit-Raj-14** [comment]
@WolfSlayer2 
Hello,
I checked your code and it seems that the feature I asked you to make the text color dark when hovered did not work.
Please recheck whether it works or not. It would be good if you attach a screenshot here on the feature you worked.

Also, the readme.md files looks ok. All you need is to add a hosted live link of the alarm clock and your pr is good to go.

Looking forward to your contribution.

**Comment by WolfSlayer2** [comment]
@Harshit-Raj-14 

Capture4

As you can see button color gets a little darker and the text color is white so u want to make it some other color ??
Capture5

i will add host link after u can confirm me about text color

**Comment by Harshit-Raj-14** [comment]
@WolfSlayer2 Its okay now, you can add the link and i will merge it. Thank you.

**Comment by WolfSlayer2** [comment]
Done adding the link, thank u.

**Comment by Harshit-Raj-14** [comment]
@WolfSlayer2 Thank you for your contribution. The PR's have been merged. You can add more of your JS projects to this repository if you are looking to contribute in hacktoberfest.

**Pull request merged**
