### PR TITLE
created a tic tac game

### PR DESCRIPTION
**Pull request by nabinkumarshaw**

### CODE REVIEW

**Comment by Harshit-Raj-14** [comment]
@nabinkumarshaw For completing your contribution you are required to create a readme file in your tictactoe folder with the following details -   project name, tech stack used, a short description and features of project written point-wise, and a live link of the project hosted on github.

Also, when making the commit attach a screenshot of your live project here.

Once you do the following changes I will merge the PR and label it as hacktoberfest accepted.

Looking forward to your contribution.

Do contact me if you need help.

**Comment by nabinkumarshaw** [comment]
Yes,as you informed me to do some changes,I have done that added README.md
with full description.and added the output link too,so its my request to
you to update the process as soon as possibly .

**Comment by Harshit-Raj-14** [comment]
@nabinkumarshaw Sorry for the delay. Your contribution has been accepted. Thank you. You can keep contributing more projects.

**Comment by nabinkumarshaw** [comment]
Thanks bhaiya....No such problem

**Pull request merged**
