### PR TITLE
website for various google searches

### PR DESCRIPTION
**Pull request by Datannotation**
A simple website using HTML and CSS to do simple google search, image search and advanced search.

### CODE REVIEW

**Comment by Harshit-Raj-14** [comment]
@coding-with-parthasarathi nice work with your project. I used your website and before accepting this contribution I want you to make just one more change to your project to make it even better.
The text box where user enters text is invisible until someone tries to click there. So, it remains completely invisible until a user clicks on textbox. this can be bad for users if they do not know where that ext box is. Just add an initial highlight shadow or text border color to your text box. And this project is good to go.
I am sure it will not take much time. Lets make this project a worthy contribution and I am looking forward to it.

**Review by Datannotation — COMMENTED** [review]
Darkened the border and added hover feature

**Comment by Harshit-Raj-14** [comment]
@coding-with-parthasarathi Project approved and merged. Can you just do one more thing that is implement the same changes in your repository from where you hosted the website. So, the changes you made here also reflect in the website. Looking forward to more contributions.

**Comment by Datannotation** [comment]
Changes implemented in my repository. Now the changes are reflected in the website link given in the README file.

**Pull request merged**
